services:
  - type: web
    name: backend-trading-ia
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: ./start.sh
    branch: main
    region: oregon
    autoDeploy: true
